In [2]:
import numpy as np
from sympy import *
from scipy import linalg

# **BÀI 1**

In [10]:
a=np.array([[1,2,3],[0,4,5],[1,0,6]])
#  MA TRẬN HỆ SỐ KÉP
print(a)
def cofactor_matrix(matrix):
    row,col= matrix.shape
    det_matrix= np.linalg.det(matrix)
    if det_matrix !=0:
        cofactor= None
        cofactor= np.linalg.inv(matrix).T *det_matrix
        return cofactor
print(f"ma trận hệ số kép là: {cofactor_matrix(a)}")


[[1 2 3]
 [2 3 2]
 [1 3 1]]
ma trận hệ số kép là: [[-3.  0.  3.]
 [ 7. -2. -1.]
 [-5.  4. -1.]]


Ma trận liên hợp (adjoint matrix) là ma trận chuyển vị của ma trận các cofactor của một ma trận vuông.

In [9]:
#MA TRẬN LIÊN HỢP
adjoint_matrix= np.transpose(cofactor_matrix(a))
print(f"ma trân lien hơp: {adjoint_matrix}")

ma trân lien hơp: [[ 24. -12.  -2.]
 [  5.   3.  -5.]
 [ -4.   2.   4.]]


# **BÀI 2**

$ \begin{bmatrix}
x^{2}+y^{2} & x&y&1\\
x_1^{2}+y_1^{2} & x_1&y_1&1\\
x_2^{2}+y_2^{2} & x_2&y_2&1\\
x_3^{2}+y_3^{2} & x_3&y_3&1\\
\end{bmatrix} $

cho toạ độ A(-1,3), B(0,1), C(-2,0)

$ \Rightarrow $ 
$ \begin{bmatrix}
x^{2}+y^{2} & x&y&1\\
-1^{2}+3^{2} & -1&3&1\\
0^{2}+1^{2} & 0&1&1\\
-2^{2}+0^{2} & -3&0&1\\
\end{bmatrix} $


In [24]:
x,y= symbols('x,y')
mp=Matrix([[x**2+y**2,x,y,1],[(-1)**2+3**2,-1,3,1],[(0)**2+1**2,0,1,1],[(-2)**0+3**2,-3,0,1]])
mp.det()


-7*x**2 - 27*x - 7*y**2 + 18*y - 11