## **BÀI TẬP TRÊN LỚP**


In [20]:
import numpy as np
import sympy as sp


$$ \text {mat1} =\left( \begin{matrix} 0.& 0.& 0.& 0.& 0.& \\ 0.& 0.& 0.& 0.& 0.& \\ 0.& 0.& 0.& 0.& 0.& \\ 0.& 0.& 0.& 0.& 0.& \\ 0.& 0.& 0.& 0.& 0.& \end{matrix} \right) $$

In [11]:
mat1 = np.zeros([5,5])
#print(mat1)

In [12]:
mat2 = np.ones( [5,5])
print (mat2)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
mat3 = mat1 + 2* mat2
print (mat3)

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [14]:
mat4 = mat3
mat3[3][2] = 10
print (mat4)
print (mat3)

[[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]
[[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]


 **vậy mat3 thay đôi thì mat4 cũng thay dổi theo**
 

In [16]:
mat5 = np.copy(mat3)
mat3[3][2] = 10
print (mat4)
print ("")
print (mat5)

[[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]

[[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]


**vậy  mat3 thay đổi thì mat4 mat5 cũng thay đổi theo**

In [ ]:
mat6 = np.empty([4, 5])
print (mat6)


In [18]:
mat7 = np.identity(4)
print (mat7)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
mat8 = np.random.random([4,5])
print(mat8)

[[0.4328343  0.69747479 0.6905454  0.81720769 0.72769399]
 [0.50790688 0.30201996 0.54065168 0.56898134 0.20236816]
 [0.56512948 0.56050258 0.99450852 0.27535839 0.4406109 ]
 [0.1796634  0.04873492 0.01824492 0.04493235 0.14126906]]


In [24]:
M = sp.Matrix([[1, 3], [2, 4]])
print (M)



Matrix([[1, 3], [2, 4]])


## **BÀI TẬP CHƯƠNG 1**


**BÀI 1**
Điểm  môn học của một nhóm SV:


In [29]:
import numpy as np
a= np.array([[7,8,9,5],[8,7,4,6],[7,5,8,6],[6,8,5,4],[9,9,8,7],[10,8,9,8]])
print (a)


[[ 7  8  9  5]
 [ 8  7  4  6]
 [ 7  5  8  6]
 [ 6  8  5  4]
 [ 9  9  8  7]
 [10  8  9  8]]


để tính điểm trung bình của từng học sinh biết rằng BT cá nhân 10%, báo cáo 20%, giữa kì 30%, cuối kì 40%


In [1]:
nhanMT = a*[10,20,30,40]
tintb = a.mean(nhanMT, axis=1)


NameError: name 'a' is not defined