# **GIỚI THIỆU VỀ PYTHON VÀ CÁC THƯ VIỆN TÍNH TOÁN**

In [109]:
import numpy as np

# **1. Bài tập trên lớp**

#### **Lệnh: mat1 = np.zeros([5,5])**

\begin{equation}
    \text {mat1 = }
    \begin{pmatrix}
      0 & 0 & 0 & 0 & 0 \\
      0 & 0 & 0 & 0 & 0 \\
      0 & 0 & 0 & 0 & 0 \\
      0 & 0 & 0 & 0 & 0 \\
      0 & 0 & 0 & 0 & 0 \\
    \end{pmatrix}
\end{equation}


In [110]:
mat1 = np.zeros([5,5])
print(mat1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


####  **Lệnh: mat2 = np.ones([5,5])**

\begin{equation}
    \text{mat2 =} 
    \begin{pmatrix}
        1 & 1 & 1 & 1 & 1 \\
        1 & 1 & 1 & 1 & 1 \\
        1 & 1 & 1 & 1 & 1 \\
        1 & 1 & 1 & 1 & 1 \\
        1 & 1 & 1 & 1 & 1 \\
    \end{pmatrix}
\end{equation}

In [111]:
mat2 = np.ones([5,5])
print(mat2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


####  **Lệnh: mat3 = mat1 + 2*mat2**

\begin{equation}
    \text{mat3 = } 
    \begin{pmatrix}
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
    \end{pmatrix}
\end{equation}

In [112]:
mat3 = mat1 + 2* mat2
print(mat3)

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


#### **Lệnh: mat4 = mat3**

#### **Lệnh: mat3[3][2] = 10**

\begin{equation}
    \text{mat3 =}
    \begin{pmatrix}
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 10 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
    \end{pmatrix}
\end{equation}

\begin{equation}
    \text{mat4 =} 
    \begin{pmatrix}
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 10 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
    \end{pmatrix}
\end{equation}

**Vậy mat3 thay đổi thì mat4 cũng thay đổi theo**

In [113]:
mat4 = mat3
mat3[3][2] = 10
print(mat4)
print()
print(mat4)

[[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]

[[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]


#### **Lệnh: mat5 = np.copy(mat3)**

####  **Lệnh: mat3[3][2] = 10**

\begin{equation}
    \text{mat3 =} 
    \begin{pmatrix}
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 10 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
    \end{pmatrix}
\end{equation}

\begin{equation}
    \text{mat4 =} 
    \begin{pmatrix}
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 10 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
    \end{pmatrix}
\end{equation}

\begin{equation}
    \text{mat5 =}
    \begin{pmatrix}
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
    \end{pmatrix}
\end{equation}


 **Vậy mat3 thay đổi  thì chỉ có mat4 thay đổi còn mat5 không thay đổi.**

In [114]:
mat3[3][2] = 2
mat5 = np.copy(mat3)
mat3[3][2] = 10
print(mat3, mat4, mat5, sep = "\n\n")

[[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]

[[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


#### **Lệnh: mat6 = np.empty([4, 5])**

\begin{equation}
    \text{mat6 =} 
    \begin{pmatrix}
    9.01096911e-312 & 5.68175493e-322 & 0.00000000e+000 & 0.00000000e+000 &  9.34598924e-30\\
    1.16095484e-0 & 8 2.87926253e-0 & 4 9.10434209e+2 &76 4.07177685e+2 & 
    1.29541836e+\\3    
    1.17688986e &+136 6.74421134e &+217 3.99255467e &+252 1.00443548e & 55.90148570\\+    5
    1.7653915 &6e+137 8.9316868 &9e+271 4.9813153 &6e+151 1.9492067 & 153
    3.242499\\e-086
    \end{pmatrix}
\end{equation}

In [115]:
mat6 = np.empty([4, 5])
print(mat6)

[[ 2.5  5.   7.5 10.  12.5]
 [15.  17.5 20.  22.5 25. ]
 [27.5 30.  32.5 35.  37.5]
 [40.  42.5 45.  47.5 50. ]]


#### **Lệnh: mat7 = np.identity(4)**

  \begin{equation}
    \text{mat7 =} 
    \begin{pmatrix}
      1 & 0 & 0 & 0\\
      0 & 1 & 0 & 0\\
      0 & 0 & 1 & 0\\
      0 & 0 & 0 & 1\\
    \end{pmatrix}
\end{equation}

In [116]:
mat7 = np.identity(4)
print(mat7)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### **Lệnh: mat8 = np.random.random([4,5])**


\begin{equation}
    \text{mat8 =} 
    \begin{pmatrix}
        0.39028529 & 0.75540465 & 0.01568219 & 0.29453656 & 0.91118005\\
        0.03844021 & 0.51781229 & 0.97992382 & 0.12070719 & 0.35404779\\
        0.07206803 & 0.84809791 & 0.49324525 & 0.92903231 & 0.81489341\\
        0.78460077 & 0.44073672 & 0.24756567 & 0.11936058 & 0.7039666\\
    \end{pmatrix}
\end{equation}

In [117]:
# mat8 = np.rand([4,5])
mat8 = np.random.random([4,5])
print(mat8)

[[0.24912259 0.02486452 0.76978406 0.02594833 0.77836724]
 [0.92153457 0.46816985 0.51938972 0.16311615 0.94469691]
 [0.02323648 0.93857405 0.6871122  0.07588489 0.34693259]
 [0.09626164 0.11322168 0.66260705 0.46870439 0.19635055]]


# **2. Bài tập về nhà**

### **Bài 1** 
- `Điểm môn học của một nhóm SV được cho như bên dưới:`

| Sinh Viên| BT cá nhân | Báo cáo | Giữa kỳ | Cuối Kỳ |
|:--------:|:----------:|:-------:|:-------:|:-------:|
|     A    |      7     |    8    |    9    |    5    |
|     B    |      8     |    7    |    4    |    6    |
|     C    |      7     |    5    |    8    |    6    |
|     D    |      6     |    8    |    5    |    4    |
|     E    |      9     |    9    |    8    |    7    |
|     F    |     10     |    8    |    9    |    8    |

- `Tỷ lệ % điểm:`

| BT cá nhân | 10% |
|:---:|:---:|
| Báo cáo    | 20% |
| Giữ kỳ     | 30% |
| Cuối kỳ    | 40% |


In [118]:
def diemTB(a, b, c, d):
     return a * 0.1 + b * 0.2 + c * 0.3 + d * 0.4
diemSV = np.array([[7, 8, 9, 5],
                         [8, 7, 4, 6],
                         [7, 5, 8, 6],
                         [6, 8, 5, 4],
                         [9, 9, 8, 7],
                         [10, 8, 9, 8]])

tenSV = np.array(['1', '2', '3', '5', '6', '7'])
for i in range(6):
    res = diemTB(*diemSV[i])
    if res >= 5.0:
        print(f"Sinh viên thứ {tenSV[i]} có điểm là {round(res, 3)} => Đạt")
    else:
        print(f"Sinh viên thứ {tenSV[i]} có điểm là {round(res, 3)} => Không Đạt")

Sinh viên thứ 1 có điểm là 7.0 => Đạt
Sinh viên thứ 2 có điểm là 5.8 => Đạt
Sinh viên thứ 3 có điểm là 6.5 => Đạt
Sinh viên thứ 5 có điểm là 5.3 => Đạt
Sinh viên thứ 6 có điểm là 7.9 => Đạt
Sinh viên thứ 7 có điểm là 8.5 => Đạt


### **Bài 2**
Sinh ngẫu nhiên ra 2 ma trận kích thước 3 x 3 và có các phần từ nguyên từ 0 đến 10:

- a) Tính tổng phần tử của mỗi ma trận

- b) So sánh norm của vector hàng 1 và vector hàng 3 của hai ma trận

- c) Tìm ma trận C, D, E là tổng, hiệu, tích, của hai ma trận trên

`gợi ý`:  sử dụng lệnh np.randoom.radint(?, size = (?, ?))

In [119]:
Mat1 = np.random.randint(0,10,size=(3,3))
Mat2 = np.random.randint(0,10,size=(3,3))
print(Mat1)
print()
print(Mat2)

[[6 9 4]
 [2 7 2]
 [7 6 0]]

[[9 6 6]
 [8 3 2]
 [6 9 5]]


- `a) tính tổng các phần tử của mỗi ma trận`

In [120]:
def sumMatrix(list):
    tong = 0
    for i in list:
        tong += i
    return sum(tong)
sum1= sumMatrix(Mat1)
sum2= sumMatrix(Mat2)
print(f"Tổng các phần tử trong mat1 là: {sum1}")
print(f"Tổng các phần tử trong mat1 là: {sum2}")

Tổng các phần tử trong mat1 là: 43
Tổng các phần tử trong mat1 là: 54


- `b) So sánh norm của vector hàng 1 và vector hàng 3 của hai ma trận`

In [121]:
normRow_11 = np.linalg.norm(Mat1[0])
normRow_13 = np.linalg.norm(Mat1[2])
normRow_21 = np.linalg.norm(Mat2[0])
normRow_23 = np.linalg.norm(Mat2[2])
print(f"Norm của vector hàng 1 của matrix1 là: {normRow_11}")
print(f"Norm của vector hàng 3 của matrix1 là: {normRow_13}")
print(f"Norm của vector hàng 1 của matrix2 là: {normRow_21}")
print(f"Norm của vector hàng 3 của matrix2 là: {normRow_23}")

# Ham so sanh
def compare(a,b):
    if a > b:
        print("Norm của vector hàng 1 lớn hơn norm vector hàng 3")
    elif a == b:
        print("Norm của vector hàng 1 bằng norm vector hàng 3")
    elif a < b:
        print("Norm của vector hàng 1 nhỏ hơn norm vector hàng 3")
print("Kết quả so sánh mat1")
compare(normRow_11,normRow_13)
print("Kết quả so sánh mat2")
compare(normRow_21,normRow_23)

Norm của vector hàng 1 của matrix1 là: 11.532562594670797
Norm của vector hàng 3 của matrix1 là: 9.219544457292887
Norm của vector hàng 1 của matrix2 là: 12.36931687685298
Norm của vector hàng 3 của matrix2 là: 11.916375287812984
Kết quả so sánh mat1
Norm của vector hàng 1 lớn hơn norm vector hàng 3
Kết quả so sánh mat2
Norm của vector hàng 1 lớn hơn norm vector hàng 3


- `c) Tìm ma trận C, D, E là tổng, hiệu, tích, của hai ma trận trên`

In [122]:
print(f"Tổng của Matrix1 và Mtrix2 là:")
print()
print(Mat1+Mat2)
print ()
print(f"Hiệu cua Matrix1 và Matrix2 là:")
print()
print(Mat1-Mat2)
print()
print(f"Tích của Matrix1 và Matrix2 là:")
print()
print(Mat1.dot(Mat2))

Tổng của Matrix1 và Mtrix2 là:

[[15 15 10]
 [10 10  4]
 [13 15  5]]

Hiệu cua Matrix1 và Matrix2 là:

[[-3  3 -2]
 [-6  4  0]
 [ 1 -3 -5]]

Tích của Matrix1 và Matrix2 là:

[[150  99  74]
 [ 86  51  36]
 [111  60  54]]


## **Bài Tập 3** 
Hãy dùng lệnh để sinh ra vector độ dài 21 với các phần tử từ a đến b nào đó. Chẳng hạn: 

a = 0, b = 100 hoặc a = 10.5, b = 50.

- a) Dùng lệnh split, chia nhỏ vector kia ra thành 3 vector con, đặt là u, v, w.

- b) Tính u*v và v.dot(w)

- c) Tính shape của u trước và sau khi transpose, nhận xét.

*Gợi ý: lệnh np.linspace(a, b, c) với a, b là các số thực và c là số nguyên dương cho biết 
số phần tử cách đều nhau trong [a;b]*

In [123]:
vector = np.linspace(0,50,21)
print(vector)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5 25.  27.5 30.  32.5
 35.  37.5 40.  42.5 45.  47.5 50. ]


`a) Dùng lệnh split, chia nhỏ vector kia ra thành 3 vector con, đặt là u, v, w.`

In [1]:
u , v, w = np.split(vector,[7,14])
print(u)
print(v)
print(w)

NameError: name 'np' is not defined

`b) Tính u*v và v.dot(w)`

In [125]:
print("Kết quả  u*v là: ")
print(u*v)
print()
print("Kết quả của v.dot(w) là: ")
print(v.dot(w))

Kết quả  u*v là: 
[  0.   50.  112.5 187.5 275.  375.  487.5]

Kết quả của v.dot(w) là: 
7612.5


`c)Tính shape của u trước và sau khi transpose, nhận xét.`

In [126]:
print("Shape của u trước khi transpose là: ",u.shape)
u1 = u.reshape((u.shape[0], 1))
print("Shape của u sau khi transpose là: ",u1.shape)


Shape của u trước khi transpose là:  (7,)
Shape của u sau khi transpose là:  (7, 1)


=> vậy trước đi transpose, u kích thước là 7 tức là 1 dòng 7 cột. Sau khi transpose (chuyển vị) thì vector u có kích thước là (7,1) tức 7 dòng 1 cột