In [2]:
from scipy import linalg
import numpy as np 
import math as m 


# **BÀI TẬP MINH HOẠ**
Ba ông Cảnh, Tùng, Hiếu dự định sẽ mua cuốn, bún, bánh ngọt và bánh mì với số lượng khác
nhau. Được biết, 4 loại hàng hóa này được bày bán tại 2 siêu thị. Như vậy, mỗi người này nên
chọn mua ở cửa hàng nào để tổng tiền là ít nhất. Giả định, nhu cầu của mỗi người và giá mỗi sản
phẩm được cho ở mỗi cửa hàng như dưới đây:

| |Cuốn|Bún|Bánh ngọt|Bánh mì|
|:--|:---:|:---:|:---------:|:-------:|
|Cảnh|6|5|3|1|
|Tùng|3|6|2|2|
|Hiếu|3|4|3|1|

**Giá tại mỗi siêu thị**
||S1|S2|
|:--|:-----:|-----:|
|Cuốn|1.50|1.00|
|Bún|2.00|2.50|
|Bánh ngọt|5.00|4.50|
|Bánh mì|16.00|17.00|





In [11]:
a= np.matrix([[6,5,3,1],[3,6,2,2],[3,4,3,1]])
b= np.matrix([[1.50,1.00],[2.00,2.50],[5.00,4.50],[16.00,17.00]])
print(a)
print()
c = a@b
print(c)

[[6 5 3 1]
 [3 6 2 2]
 [3 4 3 1]]

[[50.  49. ]
 [58.5 61. ]
 [43.5 43.5]]


In [17]:
import numpy as np

def generate_invertible_matrix(n):
    while True:
        # Tạo ma trận ngẫu nhiên
        E = np.random.randint(-10, 10, size=(n, n))
        
        # Kiểm tra tính khả nghịch
        if np.linalg.matrix_rank(E) == n:
            return E

# Kích thước ma trận
n = 3

# Tạo ma trận khả nghịch
invertible_matrix = generate_invertible_matrix(n)

print("Ma trận khả nghịch:")
print(invertible_matrix)

a= np.matrix([13,11,17])
c = a@invertible_matrix
print(c)

Ma trận khả nghịch:
[[ 9  9  9]
 [ 6 -5  9]
 [-6  1  1]]
[[ 81  79 233]]


# **CÂU 1** 

a. Tự chọn một ma trận khả nghịch 3x3. Sinh viên chứng minh ma trận đó khả nghịch (tồn
tại ma trận nghịch đảo)

b. Nhập họ và tên hoặc mã số sinh viên (của sinh viên).

c. Mã hóa họ và tên hoặc mã số sinh viên (của sinh viên).

d. Thực hiện giải mã với ma trận được chọn.

In [2]:
import numpy as np
#a
a = np.matrix([[12, 5, 2], [-1, 0, 3], [1, -1, -4]])
if np.linalg.det(a) ==0:
    print("ma tran ko kha nghich")
else:
    print("ma tran kha nghich")



ma tran kha nghich


In [21]:
#b
hoten =  input("nhập ho va ten: ")
bangma = {' ': 5, 'A':6,'Ă':7,
          'Â':8,'B':9,'C':10,'D':11,'Đ':12,'E':13,'Ê':14,'G':15,'H':16,
          'I':17,'K':18,'L':19,'M':20,'N':21,'O':22,
          'Ơ':23,'Ô':24,'P':25,'Q':26,'R':27,'S':28,
          'T':29,'U':30,'Ư':31,'V':32,'X':33,'Y':34,
          'SẮC':0,'`':1,'?':2,'~':3,'.':4}

matrices = [np.array([bangma[char] for char in word]) for word in hoten.split()]
# print("ma trận giả định là: ")

# e = np.matrix([[1,-2,2],[-1,1,3],[1,-1,-4]])
for index, matrix in enumerate(matrices):
    print("Mã chuỗi số tương ứng với từ '{}' là:".format(hoten.split()[index]))
    print(matrix)
    print("mã chuỗi số tương ứng là: ")
    matrix-=5
    print(matrix)
    encoded_matrix = np.matmul(matrix, e)
    print("Mã hóa chuỗi là:")
    print(encoded_matrix)
    
    

Mã chuỗi số tương ứng với từ 'VIEN' là:
[32 17 13 21]
mã chuỗi số tương ứng là: 
[27 12  8 16]


# **CÂU 2**

In [30]:
r = float (input())
print ("Circumference =", (r*r)*3.14)

Circumference = 176.625
