# ĐỀ KIỂM TRA THƯỜNG KỲ 1
## Môn: Đại số tuyến tính tính toán
## Ngày: 01/03/2024
## Lớp: DHKHDL18A - Nhóm TH1 & TH2. Thời gian: 90 phút
## Họ và Tên: Nguyễn Thị Viên
## MSSV: 22003025

**Câu 1.** (3 điểm) Cho hai ma trận $A$ và $B$ xác định như sau $$A=\begin{bmatrix} 2 & 3 & -1\\0 & -3 & 1\\1&1&-1 \end{bmatrix}, B = \begin{bmatrix} 0 & 3 & -3\\-1 & 2 & 0\\-4&4&1 \end{bmatrix}.$$

a) Tính $AB$, $BA^T$ và $rank(AB)$.

b) Ma trận $BA$ là ma trận suy biến hay không? Tại sao?

c) Tìm tất cả các ma trận xác định dương $C$ cấp $3$ thoả mãn $BC=BAC^{2024}+C^T$.

In [1]:
import numpy as np 

In [11]:
# A
A = np.matrix([[2,3,-1],[0,-3,1],[1,1,-1]])
B= np.matrix([[0,3,-3],[-1,2,0],[-4,4,1]])

AB= np.dot(A,B)
print(f"AB: {AB}")

BA_T= B@(A.T)
print(f"BA_T: {BA_T}")
# hạng
rank_AB= np.linalg.matrix_rank(AB)
print(f"hạng: {rank_AB}")

# B
det_BA= np.linalg.det(B@A)
print(f"det BA: {det_BA}")



AB: [[ 1  8 -7]
 [-1 -2  1]
 [ 3  1 -4]]
BA_T: [[ 12 -12   6]
 [  4  -6   1]
 [  3 -11  -1]]
hạng: 3
det BA: -36.0


## => vậy ma trận BA không suy biến vì đây là ma trận vuông và có định thức khác 0

In [ ]:
# C



**Câu 2.** (2 điểm) Một đoàn xe tải chở $290$ tấn xi măng cho một công trình xây đập thuỷ điện. Đoàn xe gồm $57$ chiếc gồm $3$ loại: xe chở $3$ tấn, xe chở $5$ tấn và xe chở $7.5$ tấn. Nếu dùng tất cả xe chở $7.5$ tấn chở ba chuyến thì được số xi măng bằng tổng số xi măng do xe $5$ tấn chở ba chuyến và xe $3$ tấn chở hai chuyến. 

a) Gọi $x_1,x_2,x_3$ lần lượt là số xe tải chở $3$, $5$ và $7.5$ tấn và đặt $X=\begin{bmatrix} x_1 & x_2 & x_3 \end{bmatrix}^T$. Mô hình hoá bài toán trên dưới dạng hệ phương trình tuyến tính $AX=b$, bằng cách tìm $A$ và $b$.

b) Tính số xe mỗi loại bằng ít nhất hai cách.


vì có ba loại xe nên ta có
$$ x_1+x_2+x_3= 57 ~~(1) $$
vì Đoàn xe gồm $57$ chiếc gồm $3$ loại: xe chở $3$ tấn, xe chở $5$ tấn và xe chở $7.5$ tấn nên ta có
$$ 3x_1+5x_2+7.5x_3=290~~(2)$$
vì dùng tất cả xe chở $7.5$ tấn chở ba chuyến thì được số xi măng bằng tổng số xi măng do xe $5$ tấn chở ba chuyến và xe $3$ tấn chở hai chuyến nên ta có:
$$ 6x_1+15x_2+22.5x_3=0~~(3)$$
từ (1)(2)(3) ta có hệ phương trình
$$ \begin{cases}
    x_1&+&x_2&+&x_3&=& 57\\
    3x_1&+&5x_2&+&7.5x_3&=&290\\
    6x_1&+&15x_2&-&22.5x_3&=0
    \end{cases}$$

Vậy hệ phương trình tuyến tính $AX=b$


Vậy hệ phương trình tuyến tính $AX=b$
$$ \begin{bmatrix}
    1&1&1\\
    3&5&7.5\\
    6&15&-22.5
    \end{bmatrix}

    \begin{bmatrix}
        x_1\\
        x_2\\
        x_3
    \end{bmatrix}

    =
    \begin{bmatrix}
    57\\
    290\\
    0
    \end{bmatrix}
    

In [8]:
import numpy as np

A1 = np.array([[1,1,1], [3,5,7.5], [6,15,-22.5]])
b1 = np.array([57, 290, 0])
# c1
c=np.linalg.solve(A1, b1)
print(c)
# c2
print(np.linalg.inv(A1)@b1)

[20. 19. 18.]
[20. 19. 18.]


**Câu 3.** (3 điểm) Cho ma trận $A$ được xác định bởi $$A=\begin{bmatrix} 
1 & 1 & 2\\
2 & -1 & 1\\
-2 & 4 & 1
\end{bmatrix}.$$
Tìm hai ma trận $Q$ và $R$ thoả mãn $A=QR$, biết $Q$ là ma trận gồm các vector cột trực chuẩn và $R$ là ma trận tam giác trên khả nghịch. Sinh viên tính toán theo từng bước dưới đây và sau đó dùng thư viện thích hợp để kiểm tra lại.

**Bước 1.** Các vector cột của $A$ là:
$$u_1 = [1,2,-2 ]^T, \, u_2 = [ 1, -1,4 ]^T, \, u_3 = [ 2,1,1 ]^T.$$

**Bước 2.** Trực giao hóa họ các vector bằng thuật giải Gram-Schmidt (để thuận tiện, ta viết vector theo dòng)

$$v_1 = u_1 = (1, 2, -2),$$
$$\left\| v_1 \right\|^2 = 9 $$
$$\left\langle u_2,v_1 \right\rangle = -9$$
$$v_2 = u_2 - \frac{\left\langle u_2,v_1 \right\rangle}{\left\| v_1 \right\|^2} v_1 = (2,1,2)$$
$$\left\| v_2 \right\|^2 = 9 $$
$$\left\langle u_3,v_1 \right\rangle = 2$$
$$\left\langle u_3,v_2 \right\rangle = 7$$
$$v_3 = u_3 - \frac{\left\langle u_3,v_1 \right\rangle}{\left\| v_1 \right\|^2} v_1 - \frac{\left\langle u_3,v_2 \right\rangle}{\left\| v_2 \right\|^2} v_2 =(\frac{2}{9}, \frac{-2}{9},\frac{1}{9})$$
$$\left\| v_3 \right\|^2 = \frac{1}{9} $$
Kết luận họ trực giao là:
$$v_1 = (1,2,-2), v_2 = (2,1,2), v_3 = (\frac{2}{9},\frac{-2}{9},\frac{1}{9}).$$

**Bước 3.** Tìm ma trận $Q$: chuẩn hóa họ các vector ở trên, ta được
$$q_1 = \frac{v_1}{\left\| v_1 \right\|} = \frac{1}{3}(1,2,-2)$$
$$q_2 = \frac{v_2}{\left\| v_2 \right\|} = \frac{1}{3}(2,1,2)$$
$$q_3 = \frac{v_3}{\left\| v_3 \right\|} = \frac{1}{3}(2,-2,1)$$
Từ đó có ma trận $Q$ là:
$$Q=\left[ \begin{matrix}
   {{q}_{1}} & {{q}_{2}} & {{q}_{3}}  \\
\end{matrix} \right]=\left[ \begin{matrix}
   {\frac{1}{3}} & {\frac{2}{3}} & {\frac{2}{3}}  \\
   {\frac{2}{3}} & {\frac{1}{3}} & {\frac{-2}{3}}  \\
   {\frac{-2}{3}} & {\frac{2}{3}} & {\frac{1}{3}}  \\
\end{matrix} \right]$$

**Bước 4.** Tìm ma trận $R$: ta tính các tích vô hướng sau đây
$$\left\langle {{u}_{1}},{{q}_{1}} \right\rangle = -3 $$
$$\left\langle {{u}_{2}},{{q}_{1}} \right\rangle = 3 $$
$$\left\langle {{u}_{3}},{{q}_{1}} \right\rangle = \frac{-2}{3}$$
$$\left\langle {{u}_{2}},{{q}_{2}} \right\rangle = -3, $$
$$\left\langle {{u}_{3}},{{q}_{2}} \right\rangle =\frac{-7}{3}, $$
$$\left\langle {{u}_{3}},{{q}_{3}} \right\rangle = \frac{1}{3}, $$
Từ đó ta có ma trận $R$ là:

$$R=\left[ \begin{matrix}
   \left\langle {{u}_{1}},{{q}_{1}} \right\rangle  & \left\langle {{u}_{2}},{{q}_{1}} \right\rangle  & \left\langle {{u}_{3}},{{q}_{1}} \right\rangle   \\
   0 & \left\langle {{u}_{2}},{{q}_{2}} \right\rangle  & \left\langle {{u}_{3}},{{q}_{2}} \right\rangle   \\
   0 & 0 & \left\langle {{u}_{3}},{{q}_{3}} \right\rangle   \\
\end{matrix} \right]=\left[ \begin{matrix}
   {1} & {1} & {2}  \\
   {2} & {-1} & {1}  \\
   {-2} & {4} & {1}  \\
\end{matrix} \right]$$

In [3]:
# Dùng thư viên thích hợp kiểm tra
import numpy as np
A = np.array([[1,1,2],[2,-1,1],[-2,4,1]])
Q, R = np.linalg.qr(A)  
print(np.round(Q,decimals = 6))
print(np.round(R,decimals = 6))
print(Q@R)

[[-0.333333 -0.666667  0.666667]
 [-0.666667 -0.333333 -0.666667]
 [ 0.666667 -0.666667 -0.333333]]
[[-3.        3.       -0.666667]
 [ 0.       -3.       -2.333333]
 [ 0.        0.        0.333333]]
[[ 1.  1.  2.]
 [ 2. -1.  1.]
 [-2.  4.  1.]]


**Câu 4.** (2 điểm) Cho $A$ là ma trận vuông cấp $2$ có hai giá trị riêng là $1$ và $-2$, với hai vector riêng tương ứng là $(1,0)$ và $(1,-1)$.

a) Tìm $A^{2024}$.

b) Tìm các giá trị riêng của $A^{2024}$.

## --------------------------------------- Hết --------------------------------------

### Lưu ý: sinh viên không được sử dụng internet. Giám thị không giải thích gì thêm.