In [2]:
import numpy as np 


In [4]:
#tạo 1 ma trận
A = np.array([(1,2,3),(4,5,6),(6,7,8)])

#in ra kiểu dữ liệu đó là gì 
print (type(A))

#xem số chiều ma trận
print(A.ndim)
#xem số phần tử thì .size
#kiểu dữ liệu của từng phân ftuwr thì .dtype

<class 'numpy.ndarray'>
2


In [11]:
A= np.array([(1,2,3),(4,5,6)])
B=np.array([(6,7,8),(8,9,10)])
print(np.subtract(A,B)) #trừ
print()
print(np.add(A,B)) #cong

#nhân 
#print(np.dot(A,B))

#chuyển vị
print(A.transpose())

[[-5 -5 -5]
 [-4 -4 -4]]

[[ 7  9 11]
 [12 14 16]]
[[1 4]
 [2 5]
 [3 6]]
