# BÀI TẬP CHƯƠNG 2

### ***Câu 1: Hãy sử dụng numpy để giải các phương trình sau:***

***Problem1: Find the point of intersection of the lines x-y=-2 and 2x+3y=6 in $\mathbb{R}^2$***
$$\begin{align}\begin{cases} x-y=-2 \\ 2x+3y=6 \end{cases}\end{align}$$
$KQ: \begin{align}\begin{cases} x=0 \\ y=2 \end{cases}\end{align}$

In [5]:
import numpy as np
matA = np.matrix([[1,-1],[2,3]])
matB = np.matrix([[-2],[6]])
matC = np.linalg.solve(matA,matB)
print(matC)

[[0.]
 [2.]]


***Problem2: Find the point of intersection of the planes x-y=2,2x-y-z=3 and x+y+z=6 in $\mathbb{R}^3$***
$$\begin{align}\begin{cases} x-y=2 \\ 2x-y-z=3 \\ x+y+z=6 \end{cases}\end{align}$$
$KQ: \begin{align}\begin{cases} x=3\\ y=1 \\ z=2 \end{cases}\end{align}$

In [9]:
import numpy as np
matA = np.matrix([[1,-1,0],[2,-1,-1],[1,1,1]])
matB = np.matrix([[2],[3],[6]])
matC = np.linalg.solve(matA,matB)
print(matC)

[[3.]
 [1.]
 [2.]]


***Problem3: Find a quadratic polynomial $p(x) = ax^2 +bx +c$ such that p(1) = 4, p(2) = 3, p(3) = 4***
$$p(x) = x^2 - 4x + 7 $$

In [10]:
import numpy as np
matA = np.matrix([[1,1,1],[4,2,1],[9,3,1]])
matB = np.matrix([[4],[3],[4]])
matC = np.linalg.solve(matA,matB)
print(matC)

[[ 1.]
 [-4.]
 [ 7.]]


***Problem4: Evaluate $\int_{0}^{1}\frac{x(x-3)}{(x-1)^2(x+2)}dx$***
$$R(x) = \frac{1}{9(x-1)} - \frac{2}{3(x-1)^2} + \frac{10}{9(x-2)}$$

In [27]:
import numpy as np
from fractions import Fraction as f

matA = np.matrix([[1, 0, 1], [1, 1, -2], [-2, 2, 1]])
matB = np.matrix([[1], [-3], [0]])
matC = np.linalg.solve(matA, matB)

print(matC)

[[-0.11111111]
 [-0.66666667]
 [ 1.11111111]]


 ### ***Câu 2: Hãy viết các câu lệnh của sympy để giải các phương trình ở Câu 1***

***Problem1: Find the point of intersection of the lines x-y=-2 and 2x+3y=6 in $\mathbb{R}^2$***
$$\begin{align}\begin{cases} x-y=-2 \\ 2x+3y=6 \end{cases}\end{align}$$
$KQ: \begin{align}\begin{cases} x=0 \\ y=2 \end{cases}\end{align}$

In [30]:
import sympy as sp
x = sp.Symbol('x')
y = sp.Symbol('y')
sp.solve([x-y+2,2*x+3*y-6],[x,y])

{x: 0, y: 2}

***Problem2: Find the point of intersection of the planes x-y=2,2x-y-z=3 and x+y+z=6 in $\mathbb{R}^3$***
$$\begin{align}\begin{cases} x-y=2 \\ 2x-y-z=3 \\ x+y+z=6 \end{cases}\end{align}$$
$KQ: \begin{align}\begin{cases} x=3\\ y=1 \\ z=2 \end{cases}\end{align}$

In [31]:
import sympy as sp
x = sp.Symbol('x')
y = sp.Symbol('y')
z = sp.Symbol('z')
sp.solve([x-y-2,2*x-y-z-3,x+y+z-6],[x,y,z])

{x: 3, y: 1, z: 2}

***Problem3: Find a quadratic polynomial $p(x) = ax^2 +bx +c$ such that p(1) = 4, p(2) = 3, p(3) = 4***
$$p(x) = x^2 - 4x + 7 $$

In [3]:
import sympy as sp
x = sp.Symbol('x')
y = sp.Symbol('y')
z = sp.Symbol('z')
sp.solve([x+y+z-4, 4*x+2*y+z-3, 9*x+3*y+z-4],[x,y,z])

{x: 1, y: -4, z: 7}

***Problem4: Evaluate $\int_{0}^{1}\frac{x(x-3)}{(x-1)^2(x+2)}dx$***
$$R(x) = \frac{1}{9(x-1)} - \frac{2}{3(x-1)^2} + \frac{10}{9(x-2)}$$

In [4]:
import sympy as sp
a = sp.Symbol('x')
b = sp.Symbol('y')
c = sp.Symbol('z')
sp.solve([x+z-1,x+y-2*z+3,-2*x+2*y+z],[x,y,z])

{x: -1/9, y: -2/3, z: 10/9}

#### ***Câu 3: Tính lũy thừa bậc k của ma trận $F_k = \left (\begin{matrix} 1& 1 \\ 1& 0 \end{matrix}\right)^n$ và chứng minh ma trận $𝑭_k$ chứa 3 phần tử của $𝐹𝑖𝑏𝑜_{k+1}, 𝐹𝑖𝑏𝑜_𝑘$ và $𝐹𝑖𝑏𝑜_{𝑘−1}$ của dãy Fibonacci (bắt đầu bằng 0 từ phần tử 0)***

In [1]:
import numpy as np

def mat_pow_k (matA, k) :
    matB = np.linalg.matrix_power(matA, k)
    return matB

def is_Fibo(a,b,c) :
    if a+b==c or a+c==b or b+c==a:
        return True

k = int(input("nhap k: "))
matA = np.array([[1,1],[1,0]])
matA_pow_k = mat_pow_k(matA,k)

a = matA_pow_k[0][0]
b = matA_pow_k[0][1]
c = matA_pow_k[1][0]
d = matA_pow_k[1][1]

if is_Fibo(a,b,c) == True or is_Fibo(a,b,d) == True or is_Fibo(a,c,d) == True or is_Fibo(b,c,d) == True  :
    print("ma tran chua 3 phan tu thuoc day fibonanci")


ma tran chua 3 phan tu thuoc day fibonanci
